name: Deploy to Cloudflare Workers

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: false
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4

      - name: Create wrangler.toml
        env:
          USERNAME: ${{ secrets.USERNAME || '_user' }}
          PASSWORD: ${{ secrets.PASSWORD || '_pass' }}
          BUCKET_NAME: ${{ secrets.BUCKET_NAME || 'bucket' }}
        run: |
          sed -e "s/\$USERNAME/$USERNAME/g" \
              -e "s/\$PASSWORD/$PASSWORD/g" \
              -e "s/\$BUCKET_NAME/$BUCKET_NAME/g" \
              wrangler.toml.template > wrangler.toml
          cat wrangler.toml

      - name: Build & Deploy Worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
